### ISSUE TITLE
Możliwość ruszania się do przodu/tyłu oraz obracania w miejscu w lewo/prawo

### ISSUE THREAD

**Issue by Wihmajster** [pw-eiti-anro-21l/brzezinski_nowakowski#3]
Możliwość ruchu za pomocą aż 4 różnych klawiszy, które odpowiadałyby odpowiednio ruchowi do przodu, do tyłu, obrotowi w lewo oraz obrotowi w prawo, bardzo rozszerzyłaby zastosowanie projektu, mógłby być on nawet użyteczny i prawie zgodny z zadaniem laboratoryjnym

**Comment by Casperus99** [comment]
Uwydatnienie zostało dodane w ostatnim commicie.
